const cuisineCategories = {
  AmericanBBQ: [
    "American",
    "Barbecue",
    "Hamburgers",
    "Hotdogs",
    "Soul Food",
    "Steak",
  ],
  Asian: [
    "Chinese",
    "Japanese",
    "Korean",
    "Thai",
    "Vietnamese/Cambodian/Malaysia",
    "Indian",
    "Filipino",
    "Indonesian",
    "Bangladeshi",
  ],
  European: [
    "Italian",
    "French",
    "Greek",
    "Irish",
    "German",
    "Armenian",
    "Russian",
    "Polish",
    "Portuguese",
    "Czech",
    "English",
    "Spanish",
    "Tapas",
  ],
  Latino: [
    "Mexican",
    "Latin (Cuban, Dominican, Puerto Rican, South & Central American)",
    "Peruvian",
    "Caribbean",
    "Brazilian",
  ],
  African: [
    "Middle Eastern",
    "Moroccan",
    "Egyptian",
    "Ethiopian",
    "Afghan",
    "African",
    "Pakistani",
  ],
  Healthy: ["Vegetarian", "Salads", "Juice, Smoothies, Fruit Salads"],
  Desserts: [
    "Bakery",
    "Donuts",
    "Ice Cream, Gelato, Yogurt, Ices",
    "Pancakes/Waffles",
    "Bagels/Pretzels",
  ],
  Beverages: [
    "Café/Coffee/Tea",
    "CafÃ©/Coffee/Tea",
    "Bottled beverages, including water, sodas, juices, etc.",
  ],
  Seafood: ["Seafood"],
  Fusion: [
    "Chinese/Japanese",
    "Chinese/Cuban",
    "Pizza/Italian",
    "Sandwiches/Salads/Mixed Buffet",
    "Soups & Sandwiches",
  ],
  FastFood: ["Pizza", "Pizza/Italian", "Sandwiches"],
  Other: [
    "Other",
    "Not Listed/Not Applicable",
    "Delicatessen",
    "Continental",
    "Eastern European",
  ],
};

module.exports = cuisineCategories;
